### ISSUE TITLE
secret_key problem

### ISSUE THREAD

**Issue by misakar** [neo1218/muxi#2]
Traceback (most recent call last):
  File "/Users/apple/hack/muxi/muxi/muxi.py", line 396, in **call**
    return self.wsgi_app(environ, start_response)
  File "/Users/apple/hack/muxi/muxi/muxi.py", line 384, in wsgi_app
    with ActiveRequestContext(self, environ):
  File "/Users/apple/hack/muxi/muxi/muxi.py", line 207, in **enter**
    _request_ctx_stack.push(_RequestContext(self.app, self.environ))
  File "/Users/apple/hack/muxi/muxi/muxi.py", line 95, in __init__
    self.session = app.open_session(self.request)
  File "/Users/apple/hack/muxi/muxi/muxi.py", line 317, in open_session
    secret_key=key
  File "/Library/Python/2.7/site-packages/werkzeug/contrib/securecookie.py", line 298, in load_cookie
    data = request.cookies.get(key)
  File "/Library/Python/2.7/site-packages/werkzeug/local.py", line 338, in **getattr**
    return getattr(self._get_current_object(), name)
  File "/Library/Python/2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/Users/apple/hack/muxi/muxi/muxi.py", line 53, in <lambda>
    request = LocalProxy(lambda: _request_ctx_stack.top.request) #|
AttributeError: 'NoneType' object has no attribute 'request'

**Comment by misakar** [comment]
secret_key 有毒呀！！

**Comment by misakar** [comment]
request.cookies => {}
This may be the problem!!!!

**Comment by misakar** [comment]
![2015-11-14 1 42 46](https://cloud.githubusercontent.com/assets/10671733/11153022/18c48a2e-8a71-11e5-93d2-07225a4509ed.png)

**Comment by misakar** [comment]
but, if key is not exist, request.cookies.get(key) will return None not error .....

**Comment by misakar** [comment]
![2015-11-14 1 59 05](https://cloud.githubusercontent.com/assets/10671733/11153355/53022f00-8a73-11e5-8742-a6c9d00bf4e8.png)
so, the problem is here:<code> global request in</code> :8ball: <code>func:open_session</code>

**Comment by misakar** [comment]
![2015-11-14 5 55 57](https://cloud.githubusercontent.com/assets/10671733/11162999/0216c1a6-8af9-11e5-851e-bd84c5988dc2.png)
果然是这个...(hahaha, 做好了用处还是很大大的.)

**Comment by misakar** [comment]
![2015-11-14 6 24 05](https://cloud.githubusercontent.com/assets/10671733/11163072/9862063a-8afd-11e5-83d9-0cbe33530f7a.png)
Yes, If I change it to <code>test request</code>, it work!

```
from werkzeug.test import create_environ
from werkzeug.wrappers import Request

environ = create_environ()
Request(environ)
```
